### ISSUE TITLE
Homebrew error with nix-darwin - "Error: invalid option: --no-lock"

### ISSUE THREAD

**Issue by victorhooi** [LnL7/nix-darwin#1369]
I have a macOS 15.3.1 (Sequioia) machine. I've installed Nix using the Determinate Systems NIx installer (**not** the Determinate distro, but vanilla Nix) and installed nix-darwin per the nix-darwin README.

I then edited `/etc/nix-darwin/flake.nix`, to add a Homebrew section:
```
victorhooi@MacBook-Pro:/etc/nix-darwin/ > cat flake.nix 
{
  description = "Example nix-darwin system flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nix-darwin.url = "github:LnL7/nix-darwin/master";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = inputs@{ self, nix-darwin, nixpkgs }:
  let
    configuration = { pkgs, ... }: {
      # List packages installed in system profile. To search by name, run:
      # $ nix-env -qaP | grep wget
      environment.systemPackages =
        [ pkgs.vim
        ];

      homebrew = {
        enable = true;
        # onActivation.cleanup = "uninstall";

        taps = [];
        brews = [ "cowsay" ];
        casks = [];
      };


      # Necessary for using flakes on this system.
      nix.settings.experimental-features = "nix-command flakes";

      # Enable alternative shell support in nix-darwin.
      # programs.fish.enable = true;

      # Set Git commit hash for darwin-version.
      system.configurationRevision = self.rev or self.dirtyRev or null;

      # Used for backwards compatibility, please read the changelog before changing.
      # $ darwin-rebuild changelog
      system.stateVersion = 6;

      # The platform the configuration will be used on.
      nixpkgs.hostPlatform = "aarch64-darwin";
    };
  in
  {
    # Build darwin flake using:
    # $ darwin-rebuild build --flake .#MacBook-Pro
    darwinConfigurations."MacBook-Pro" = nix-darwin.lib.darwinSystem {
      modules = [ configuration ];
    };
  };
}
```
After running `darwin-rebuild switch`, I get an error from Homebrew about `Error: invalid option: --no-lock`:
```
victorhooi@MacBook-Pro:/etc/nix-darwin/ > darwin-rebuild switch
building the system configuration...
Password:
setting up user launchd services...
Homebrew bundle...
Usage: brew bundle [subcommand]

Bundler for non-Ruby dependencies from Homebrew, Homebrew Cask, Mac App Store,
Whalebrew and Visual Studio Code.

brew bundle [install]:
    Install and upgrade (by default) all dependencies from the Brewfile.

You can specify the Brewfile location using --file or by setting the
$HOMEBREW_BUNDLE_FILE environment variable.

You can skip the installation of dependencies by adding space-separated values
to one or more of the following environment variables:
$HOMEBREW_BUNDLE_BREW_SKIP, $HOMEBREW_BUNDLE_CASK_SKIP,
$HOMEBREW_BUNDLE_MAS_SKIP, $HOMEBREW_BUNDLE_WHALEBREW_SKIP,
$HOMEBREW_BUNDLE_TAP_SKIP.

brew bundle upgrade:
    Shorthand for brew bundle install --upgrade.

brew bundle dump:
    Write all installed casks/formulae/images/taps into a Brewfile in the
current directory.

brew bundle cleanup:
    Uninstall all dependencies not present in the Brewfile.

This workflow is useful for maintainers or testers who regularly install lots of
formulae.

Unless --force is passed, this returns a 1 exit code if anything would be
removed.

brew bundle check:
    Check if all dependencies present in the Brewfile are installed.

This provides a successful exit code if everything is up-to-date, making it
useful for scripting.

brew bundle list:
    List all dependencies present in the Brewfile.

By default, only Homebrew formula dependencies are listed.

brew bundle edit:
    Edit the Brewfile in your editor.

brew bundle exec command:
    Run an external command in an isolated build environment based on the
Brewfile dependencies.

This sanitized build environment ignores unrequested dependencies, which makes
sure that things you didn't specify in your Brewfile won't get picked up by
commands like bundle install, npm install, etc. It will also add compiler
flags which will help with finding keg-only dependencies like openssl,
icu4c, etc.

brew bundle sh:
    Run your shell in a brew bundle exec environment.

brew bundle env:
    Print the environment variables that would be set in a brew bundle exec
environment.

      --file                       Read the Brewfile from this location. Use
                                   --file=- to pipe to stdin/stdout.
      --global                     Read the Brewfile from
                                   $HOMEBREW_BUNDLE_FILE_GLOBAL (if set),
                                   ${XDG_CONFIG_HOME}/homebrew/Brewfile (if
                                   $XDG_CONFIG_HOME is set),
                                   ~/.homebrew/Brewfile or ~/.Brewfile
                                   otherwise.
  -v, --verbose                    install prints output from commands as they
                                   are run. check lists all missing
                                   dependencies.
      --no-upgrade                 install does not run brew upgrade on
                                   outdated dependencies. check does not check
                                   for outdated dependencies. Note they may
                                   still be upgraded by brew install if
                                   needed. This is enabled by default if
                                   $HOMEBREW_BUNDLE_NO_UPGRADE is set.
      --upgrade                    install runs brew upgrade on outdated
                                   dependencies, even if
                                   $HOMEBREW_BUNDLE_NO_UPGRADE is set. 
      --install                    Run install before continuing to other
                                   operations e.g. exec.
  -f, --force                      install runs with --force/--overwrite.
                                   dump overwrites an existing Brewfile.
                                   cleanup actually performs its cleanup
                                   operations.
      --cleanup                    install performs cleanup operation, same as
                                   running cleanup --force. This is enabled by
                                   default if $HOMEBREW_BUNDLE_INSTALL_CLEANUP
                                   is set and --global is passed.
      --all                        list all dependencies.
      --formula, --brews           list or dump Homebrew formula
                                   dependencies.
      --cask, --casks              list or dump Homebrew cask dependencies.
      --tap, --taps                list or dump Homebrew tap dependencies.
      --mas                        list or dump Mac App Store dependencies.
      --whalebrew                  list or dump Whalebrew dependencies.
      --vscode                     list or dump VSCode extensions.
      --no-vscode                  dump without VSCode extensions. This is
                                   enabled by default if
                                   $HOMEBREW_BUNDLE_DUMP_NO_VSCODE is set.
      --describe                   dump adds a description comment above each
                                   line, unless the dependency does not have a
                                   description. This is enabled by default if
                                   $HOMEBREW_BUNDLE_DUMP_DESCRIBE is set.
      --no-restart                 dump does not add restart_service to
                                   formula lines.
      --zap                        cleanup casks using the zap command
                                   instead of uninstall.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -h, --help                       Show this message.
Error: invalid option: --no-lock
```

**Comment by Zeirison** [comment]
@bensleveritt I have the same issue and I installed nix from scratch today, how exactly can I "update" nix-darwin?

I've already tried:
```
nix-channel --update
nix-env -u '*'
nix-collect-garbage --delete-old
nix run --refresh nix-darwin/nix-darwin-24.11#darwin-rebuild
```

Maybe the issue can only be solved by updating to "unstable", but I wouldn't want to.

**Comment by emilazy** [comment]
> I have the same issue and I installed nix from scratch today, how exactly can I "update" nix-darwin?
> 
> I've already tried:
> 
> ```
> nix-channel --update
> nix-env -u '*'
> nix-collect-garbage --delete-old
> nix run --refresh nix-darwin/nix-darwin-24.11#darwin-rebuild
> ```
> 
> Maybe the issue can only be solved by updating to "unstable", but I wouldn't want to.
> 
> Thanks!

@Zeirison If you’re using a flake, then run `nix flake update` in its directory.

> The Update now leads to the following error for me, when doing a rebuild:

@rafiv This is code you’ve added to your activation scripts (apparently it’s something people have copy‐pasted from a YouTube video a lot or something?). Using `read -r` should fix it.

**Comment by RobbieMcKinstry** [comment]
I encountered this error out of the blue today. `nix flake update` solved it immediately 👍🏻  Thank you!

**Comment by honeyyadav** [comment]
Worked like a charm, thanks @RobbieMcKinstry

**Comment by iamppborah** [comment]
`nix flake update` worked! Thanks :)

**Comment by TimoBechtel** [comment]
For anyone coming from Google because of the "Error: invalid option: --no-lock"

The `--no-lock` option was removed from `brew bundle` :)

see:
https://github.com/Homebrew/homebrew-bundle/commit/98d8ad7ddcca7e7b700cd496207d51fa042c0b00

Seems like it was a noop before so I assume it is safe to just remove the `--no-lock` flag.

_(unrelated to nix / nix-darwin)_

**Comment by sukhmel** [comment]
> I encountered this error out of the blue today. `nix flake update` solved it immediately 👍🏻 Thank you!

I'd recommend trying `nix flake update darwin` first, as full update may update inputs you don't want updated.

For me almost every time I do full flakes update I have to then cherry-pick broken packages from older versions, but maybe that's just because I'm on `unstable` by default.

**Comment by lockejan** [comment]
This has been fixed with https://github.com/LnL7/nix-darwin/pull/1362

**Comment by angabini** [comment]
@emilazy 
> If you’re using a flake, then run nix flake update in its directory.

What if not using flake, and using channels? I tried [updating nix-darwin ](https://github.com/LnL7/nix-darwin?tab=readme-ov-file#step-5-updating-nix-darwin) and still the same issue.

**Comment by mhomoky** [comment]
It now appears `brew bundle` has now been (re-)moved in homebrew as of homebrew 4.2.5. Are there any plans to update `nix-homebrew` to this latest version or is that a major change?

This bit me after doing a `nix flake update` followed by an ill-thought out `brew update` instead of `brew upgrade` – I know, I should've checked release notes 🤦🏻

**Comment by genebean** [comment]
@mhomoky we have a new issue - let's track it in https://github.com/LnL7/nix-darwin/issues/1393

**Comment by joscha** [comment]
I suddenly started seeing this this morning. Updating to 536f951efb1ccda9b968e3c9dee39fbeb6d3fdeb does not seem to make a difference. When running `which brew` I get `/opt/homebrew/bin/brew` - is that meant to be returning a nix store path? 

Update: I got it to work by changing:

```diff
         ./result/sw/bin/darwin-rebuild \
-            activate \
+            switch \
             --flake . \
             --fallback
```

**Comment by malob** [comment]
Going through open homebrew module issues. This was fixed in #1362, which removed the `--no-lock` flag. Multiple commenters have confirmed that updating nix-darwin resolves it. I think this can be closed.

cc @emilazy @Enzime
