### ISSUE TITLE
error when using nixpkgs-unstable with latest nix-darwin

### ISSUE THREAD

**Issue by jeremybernstein** [LnL7/nix-darwin#1534]
No changes to my underlying flakes, but a `nix flake update` followed by a switch results in:
 ```
building the system configuration...
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:37:12:
           36|
           37|   strict = derivationStrict drvAttrs;
             |            ^
           38|

       … while evaluating derivation 'darwin-system-25.11.e04a388'
         whose name attribute is located at «github:NixOS/nixpkgs/9b008d60392981ad674e04016d25619281550a9d?narHash=sha256-mgFxAPLWw0Kq%2BC8P3dRrZrOYEQXOtKuYVlo9xvPntt8%3D»/pkgs/stdenv/generic/make-derivation.nix:468:13

       … while evaluating attribute 'activationScript' of derivation 'darwin-system-25.11.e04a388'
         at «github:nix-darwin/nix-darwin/e04a388232d9a6ba56967ce5b53a8a6f713cdfcf?narHash=sha256-HsJM3XLa43WpG%2B665aGEh8iS8AfEwOIQWk3Mke3e7nk%3D»/modules/system/default.nix:89:7:
           88|
           89|       activationScript = cfg.activationScripts.script.text;
             |       ^
           90|

       … while evaluating the option `system.activationScripts.script.text':

       … while evaluating definitions from `/nix/store/hfdckhk2m6azhhdf7msn0nvhvcgzl30y-source/modules/system/activation-scripts.nix':

       … while evaluating the option `system.activationScripts.applications.text':

       … while evaluating definitions from `/nix/store/hfdckhk2m6azhhdf7msn0nvhvcgzl30y-source/modules/system/applications.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: Package ‘hostname-debian-3.25’ in /nix/store/1sdxl91z4didx5kp75b1ig0r2iqhmkbi-source/pkgs/by-name/ho/hostname-debian/package.nix:30 is not available on the requested hostPlatform:
         hostPlatform.config = "arm64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "powerpc64-linux"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
```
If I redirect `nixpkgs` and `nix-darwin` to the 25.05 branches, the error goes away, but I would prefer to remain on `unstable`. I'm not sure what changed in the meantime, though. Let me know if you need additional information.

**Comment by ojsef39** [comment]
same here

**Comment by hawkish** [comment]
Same error here.

**Comment by emilazy** [comment]
Should be fixed once https://github.com/NixOS/nixpkgs/pull/423643 reaches the channels.

**Comment by jeremybernstein** [comment]
...and appears to be fixed now.

**Comment by ojsef39** [comment]
i still get the issue on nixos-unstable

edit: my bad its not in **nixos**-unstable yet https://nixpk.gs/pr-tracker.html?pr=423643
