### ISSUE TITLE
flake install fails with builder error for darwin-manual-html

### ISSUE THREAD

**Issue by thuvasooriya** [LnL7/nix-darwin#907]
```text
# nix run nix-darwin -- switch --flake ~/.config/nix-darwin
# at 00:20:40 from  .config/nix-darwin

building the system configuration...
error: builder for '/nix/store/gzz3l7gjicrmmamm033xfiqphdcc0jz4-darwin-manual-html.drv' failed with exit code 1;
       last 1 log lines:
       > cp: cannot stat '/nix/store/j7zkz51ja8dr9wb1wligj7hvq6mnzyg2-source/overrides.css': No such file or directory
       For full logs, run 'nix log /nix/store/gzz3l7gjicrmmamm033xfiqphdcc0jz4-darwin-manual-html.drv'.
[5/3/19 built (1 failed), 3/0/10 copied (383.6/452.8 MiB), 59.5/70.0 MiB DL] 
building darwin-manual-html: cp: cannot stat '/nix/store/j7zkz51ja8dr9wb1wligj7hvq6mnzyg2-source/overr^error: 1 dependencies of derivation '/nix/store/65mlky03rzmzh493yyma0ja6inc0s4wc-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2q3cvl863zxghbinwrmwz7n2fxl2h8h1-darwin-system-24.05.20240317.6af7e81+darwin4.d9ea313.drv' failed to build

# nix log /nix/store/gzz3l7gjicrmmamm033xfiqphdcc0jz4-darwin-manual-html.drv
# at 00:21:08 from .config/nix-darwin

warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/gzz3l7gjicrmmamm033xfiqphdcc0jz4-darwin-manual-html.drv^*'
cp: cannot stat '/nix/store/j7zkz51ja8dr9wb1wligj7hvq6mnzyg2-source/overrides.css': No such file or directory
```

I'm really sorry if this is not the conventional way to describe an issue, 
but I just spent the whole day all day trying to figure out a way to successfully install nix and nix-darwin on my mac, guess what I'm not even close. After countless failures. I decided to start from scratch and uninstalled everything as the nix reference manual says and tried to install nix fresh with the determinate systems installer it went well but I couldn't install nix-darwin.

Any help in the right direction would be appreciated

Note: Earlier when I tried to install nix-darwin it installed sucessfully but I couldn't get the darwin-rebuild command to work in my fish shell after many tries. Not sure how the situation changed to not installing nix-darwin at all. :( 

changed "aarch64-darwin" in the flake.nix and followed through the rest of the commands

**Comment by Samasaur1** [comment]
Possibly #906?

**Comment by thuvasooriya** [comment]
> Possibly #906?

Can't believe I got pranked by a change 41 minutes ago. Thankyou very much for the quick reply 🥂 
Guess I should wait for the updated installer?

**Comment by Enzime** [comment]
Should be fixed by #906

**Comment by ShuttleSpace** [comment]
nixpkgs-23.05-darwin still exists

```sh
building the system configuration...
error: builder for '/nix/store/zav7w6a0a2aahvx2mzcaw6pg01bsakj1-darwin-manual-html.drv' failed with exit code 1;
       last 1 log lines:
       > cp: cannot stat '/nix/store/5hawysdasgnibwf8y7zmf2sqz07626pw-source/overrides.css': No such file or directory
       For full logs, run 'nix-store -l /nix/store/zav7w6a0a2aahvx2mzcaw6pg01bsakj1-darwin-manual-html.drv'.
error: 1 dependencies of derivation '/nix/store/wjkp4x6hx9sip6fifscvxiznnprwdlfb-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/48114j6kxg6ifryx2iysfzgfgxq8vgam-darwin-system-23.11.20240321.ac794a6+darwin4.afe83cb.drv' failed to bu 
```

**Comment by willgorman** [comment]
I'm seeing the issue still on `github:nixos/nixpkgs/nixpkgs-23.11-darwin`.  Trying to follow along with https://github.com/ryan4yin/nix-darwin-kickstarter/blob/main/minimal/flake.nix#L24 but running into this error.  How is possible to use the fix from https://github.com/LnL7/nix-darwin/pull/906 with that version of nixpkgs?

**Comment by willgorman** [comment]
Sorry, still pretty new at this but I see now.  I had to run `nix flake update` because the flake.lock for nix-darwin-kickstarter was pointed at older commits that did not yet have the #906 fix.
